### ISSUE TITLE
DataLoader object is not iterable

### ISSUE THREAD

**Issue by JanryPei** [Obs01ete/kaggle_latenciaga#1]
Thanks for your sharing! 

But when I run the main.py with collection "layout-xla-random", it occurs the following problem "TypeError: argument of type 'method' is not iterable".

I find the problem lies in the train_Loader, it's a method rather than an iterable object, while I confirm it's a dataloader object.

The terminal information are listed as followed.

<class 'torch.utils.data.dataloader.DataLoader'>                                                   [23/57]
Traceback (most recent call last):                                                                        
  File "/root/kaggle/src/main.py", line 846, in <module>                                                  
    main()                                                                                                
  File "/root/kaggle/src/main.py", line 841, in main                                                      
    trainer.train()                                                                                       
  File "/root/kaggle/src/main.py", line 364, in train                                                     
    for batch in train_loader:
  File "/opt/conda/envs/kaggle/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/opt/conda/envs/kaggle/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
 File "/opt/conda/envs/kaggle/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data                                                                                             
    data.reraise()                                                                                        
  File "/opt/conda/envs/kaggle/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise raise exception                                                                                       
TypeError: Caught TypeError in DataLoader worker process 0.                                               
Original Traceback (most recent call last):                                                               
  File "/opt/conda/envs/kaggle/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/kaggle/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/kaggle/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/kaggle/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 263, in __getitem__
    data = self.get(self.indices()[idx])
  File "/root/kaggle/src/data.py", line 331, in get
    if 'node_config_feat' in single_data.keys:
TypeError: argument of type 'method' is not iterable

**Comment by dmitrii-khizbullin** [comment]
Hi @JanryPei, and thanks for checking out our repo! Please let me know the version of PyG that you are using. Or, please share the output of `conda env export`.
